### PR TITLE
Basic Documentation for Core Platform Features

### PR DESCRIPTION
**Pull request by jburket**
I have written a Getting Started with the picoCTF Platform 2 guide that hits on a lot of the different topics needed to run a competition using the Platform. The target audience for this guide is someone with some coding experience who wants to setup a competition with unique problems, new web pages, and potentially new achievements. This is not a guide for users who want to understand how the Platform works or make significant API changes.

I would appreciate any feedback on the content, wording, etc. of the Getting Started guide. Is there anything critical missing? Are there things in the guide that aren't really relevant? Is anything particularly confusing?

### CODE REVIEW

**Comment by jburket** [comment]
Note that this pull request addresses issue #35.

**Comment by ManuelNM** [comment]
I recommend that you add:
1.- Create directory /home/vagrant/
2.- unzip master.zip to /home/vagrant/

**Comment by GroundPound** [comment]
As I discussed in #40, the documentation needs work regarding the deployment outside of a Vagrant environment. It sounds like we never fully tested the instructions in a non-Vagrant environment. I believe this needs to be updated before merging. I'm not sure @jburket has time these days, but maybe @cganas or @tim-becker can finish polishing this now that they maintain picoCTF.

**Comment by bobacadodl** [comment]
Can you add a brief explanation on how to properly setup the google captcha?

**Comment by GroundPound** [comment]
@bobacadodl , could you file a separate issue for adding the CAPTCHA documentation? That way if we don't address it in this pull request, it'll still be an open issue.

**Comment by royragsdale** [comment]
Merging to provide a baseline for competition hosting documentation.

**Pull request merged**
